# 查询所有的游戏
query channelGames($options:Any) {
  get(options: $options)
}

# 查询对应游戏的渠道
query channels($options: Any) {
  post(options: $options)
}
#仅仅是为了刷新所设
query refetchChannels($options: Any) {
  post(options:$options)
}

# 删除渠道
mutation deletechannel($options: Any) {
  post(options: $options)
}
# 编辑渠道信息
mutation editchannelInfo($options: Any) {
  post(options:$options)
}
# 添加新的渠道
mutation addchannelInfo($options: Any) {
  post(options:$options)
}


