query AppInfos($options: Any) {
  get(options: $options) 
}

mutation AdvChannels($options: Any) {
  post(options: $options)
}

mutation PayChannels($options: Any) {
   post(options: $options)
}

mutation PayWays( $options: Any) {
   post(options: $options)
}

mutation Products($options: Any) {
   post(options: $options)
}

mutation Verify($options: Any) {
  post(options: $options)
}

mutation Repair($options: Any) {
   post(options: $options)
}


