# 查询所有的游戏
query games($options: Any) {
  get(options: $options)
}

# 查询对应游戏的区服
query zones($options: Any) {
  post(options: $options)
}
# 版本二添加区服时查询主区信息
query mainZoneList($options: Any) {
  post(options: $options)
}

# 合区
mutation mergeZone($options: Any) {
  post(options:$options)
}
# 更改区服的信息
mutation editZoneInfo($options: Any) {
  post(options: $options)
}
# 添加新的区服
mutation addZoneInfo($options: Any) {
  post(options:$options)
}

